// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {appcore} from '../models';
import {main} from '../models';
import {tools} from '../models';

export function AddTask(arg1:config.Task):Promise<config.Task>;

export function AddTool(arg1:config.Tool):Promise<void>;

export function CheckToolUpdate(arg1:string):Promise<appcore.ReleaseView>;

export function CheckWeiboCookie():Promise<appcore.WeiboView>;

export function ClearWeiboCookie():Promise<void>;

export function CloseWindow():Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function DeleteTool(arg1:string):Promise<void>;

export function EditTool(arg1:config.Tool):Promise<void>;

export function Env():Promise<main.EnvInfo>;

export function MinimiseWindow():Promise<void>;

export function PickCookieFile():Promise<string>;

export function PickDirectory():Promise<string>;

export function PickExecutable():Promise<string>;

export function ProbeTool(arg1:string):Promise<tools.Info>;

export function Quit():Promise<void>;

export function ResetToolPath(arg1:string):Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function SaveWeiboCookie(arg1:string):Promise<appcore.WeiboView>;

export function SetToolPath(arg1:string,arg2:string):Promise<void>;

export function Settings():Promise<config.Settings>;

export function ShowWindow():Promise<void>;

export function StartTask(arg1:string):Promise<void>;

export function StopTask(arg1:string):Promise<void>;

export function TaskEvents(arg1:string):Promise<Array<appcore.EventView>>;

export function TaskForm(arg1:string):Promise<config.Task>;

export function Tasks():Promise<Array<appcore.TaskView>>;

export function ToggleMaximise():Promise<void>;

export function Tools():Promise<Array<appcore.ToolView>>;

export function UpdateTask(arg1:config.Task):Promise<config.Task>;

export function UpgradeTool(arg1:string):Promise<appcore.ReleaseView>;

export function WeiboState():Promise<appcore.WeiboView>;
