// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
  return window['go']['main']['App']['AddTask'](arg1);
}

export function AddTool(arg1) {
  return window['go']['main']['App']['AddTool'](arg1);
}

export function CheckToolUpdate(arg1) {
  return window['go']['main']['App']['CheckToolUpdate'](arg1);
}

export function CheckWeiboCookie() {
  return window['go']['main']['App']['CheckWeiboCookie']();
}

export function ClearWeiboCookie() {
  return window['go']['main']['App']['ClearWeiboCookie']();
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DeleteTool(arg1) {
  return window['go']['main']['App']['DeleteTool'](arg1);
}

export function EditTool(arg1) {
  return window['go']['main']['App']['EditTool'](arg1);
}

export function Env() {
  return window['go']['main']['App']['Env']();
}

export function MinimiseWindow() {
  return window['go']['main']['App']['MinimiseWindow']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickExecutable() {
  return window['go']['main']['App']['PickExecutable']();
}

export function ProbeTool(arg1) {
  return window['go']['main']['App']['ProbeTool'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ResetToolPath(arg1) {
  return window['go']['main']['App']['ResetToolPath'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveWeiboCookie(arg1) {
  return window['go']['main']['App']['SaveWeiboCookie'](arg1);
}

export function SetToolPath(arg1, arg2) {
  return window['go']['main']['App']['SetToolPath'](arg1, arg2);
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartTask(arg1) {
  return window['go']['main']['App']['StartTask'](arg1);
}

export function StopTask(arg1) {
  return window['go']['main']['App']['StopTask'](arg1);
}

export function TaskEvents(arg1) {
  return window['go']['main']['App']['TaskEvents'](arg1);
}

export function TaskForm(arg1) {
  return window['go']['main']['App']['TaskForm'](arg1);
}

export function Tasks() {
  return window['go']['main']['App']['Tasks']();
}

export function ToggleMaximise() {
  return window['go']['main']['App']['ToggleMaximise']();
}

export function Tools() {
  return window['go']['main']['App']['Tools']();
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}

export function UpgradeTool(arg1) {
  return window['go']['main']['App']['UpgradeTool'](arg1);
}

export function WeiboState() {
  return window['go']['main']['App']['WeiboState']();
}
