// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Env():Promise<main.EnvInfo>;

export function Quit():Promise<void>;

export function ShowWindow():Promise<void>;
